// Code generated by tcpsocks/internal/keygen; DO NOT EDIT.
//
// Repository default is an empty key. To generate and embed a key, run:
//
//	go generate ./...
package keydata

// DefaultPSKHex is a 32-byte PSK in hex form (64 characters) embedded into the binary
// when BuildPSKHex is not provided. Empty string means "not set".
const DefaultPSKHex = ""

// AutoGenerated is true when the key was generated automatically (go generate without a custom key).
const AutoGenerated = false
